###############################################################################
# Module: secrets_manager — app secrets for the FastAPI inference service
# (SEC-T3). Nothing here is ever committed: db_password flows in from the
# same TF_VAR_db_password already used by RDS, and the JWT signing key is
# generated by Terraform itself and never leaves state/Secrets Manager.
###############################################################################

resource "random_password" "jwt_signing_key" {
  length  = 64
  special = false # avoid chars that need extra escaping when read into env vars
}

resource "aws_secretsmanager_secret" "db_credentials" {
  #checkov:skip=CKV_AWS_149: Uses the AWS-managed secretsmanager key (no extra cost); a dedicated CMK is deferred for the budget lab
  #checkov:skip=CKV2_AWS_57: Automatic rotation requires a Lambda rotator and app coordination, deferred for the budget lab
  name                    = "${var.project}/${var.environment}/db-credentials"
  recovery_window_in_days = 0 # instant delete on destroy — fits the OPS-T1 destroy/rebuild runbook
  tags                    = { Project = var.project }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = var.db_username
    password = var.db_password
    host     = var.db_host
    port     = 5432
    dbname   = var.db_name
  })
}

resource "aws_secretsmanager_secret" "jwt_signing_key" {
  #checkov:skip=CKV_AWS_149: Uses the AWS-managed secretsmanager key (no extra cost); a dedicated CMK is deferred for the budget lab
  #checkov:skip=CKV2_AWS_57: Automatic rotation requires a Lambda rotator and app coordination, deferred for the budget lab
  name                    = "${var.project}/${var.environment}/jwt-signing-key"
  recovery_window_in_days = 0
  tags                    = { Project = var.project }
}

resource "aws_secretsmanager_secret_version" "jwt_signing_key" {
  secret_id     = aws_secretsmanager_secret.jwt_signing_key.id
  secret_string = random_password.jwt_signing_key.result
}
